spring:
  application:
    name: Searching And Recommend
solr:
  address: http://node2.hdp:8983/solr
  connectionTimeout: 10000
  socketTimeout: 60000
  collectionName: compCollection
server:
  port: 9000