spring:
  application:
    name: Searching And Recommend
  datasource:
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
    url: jdbc:phoenix:localhost:2181
  servlet:
      multipart:
        max-file-size: 3MB
        max-request-size: 3MB
kafka:
  history:
    topics:
      - history
    kafka-params-consumer:
      "[bootstrap.servers]": localhost:9092
      "[group.id]": history
      "[key.deserializer]": org.apache.kafka.common.serialization.StringDeserializer
      "[value.deserializer]": org.apache.kafka.common.serialization.StringDeserializer
    kafka-params-producer:
      "[bootstrap.servers]": localhost:9092
      "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
      "[value.serializer]": org.apache.kafka.common.serialization.StringSerializer
      "[linger.ms]": 1
      "acks": all
      "[batch.size]": 200
      "[client.id]": history-producer
dict:
  syn:
    zkHosts: localhost:2181
    zkPath: /test
solr:
  address: http://localhost:8983/solr
  connectionTimeout: 10000
  socketTimeout: 60000
  collectionName: compsCollection
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.manlier.srapp.domain
server:
  port: 9000
debug: true