spring:
  application:
    name: Searching And Recommend
  datasource:
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
    url: jdbc:phoenix:localhost:2181
  servlet:
      multipart:
        max-file-size: 3MB
        max-request-size: 3MB
solr:
  address: http://node2.hdp:8983/solr
  connectionTimeout: 10000
  socketTimeout: 60000
  collectionName: compCollection
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.manlier.srapp.domain
server:
  port: 9000
debug: true